famtrack/familyapp/urls.py
from django.urls import path
from . import views

#Define a list of URL patterns
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('fam/', views.FamilyListView.as_view(), name='family-list'),
    
    path('fam/<int:pk>', views.FamilyMemberDetailView.as_view(), name='family-detail'),
]

famtrack/famtrack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('familyapp.urls')),
]

famtrack/familyapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Family(models.Model):
    #Fields
    family_name = models.CharField(max_length=50, help_text="Enter family name")
    address = models.CharField(max_length=50, help_text="Enter residence address")
   
    class Meta:
        ordering = ['family_name']

    def __str__(self):
        return self.family_name

    def get_absolute_url(self):
        return reverse('family-detail',args=[str(self.id)])

class FamilyMember(models.Model):
    PARENT = 'PR'
    SON = 'SN'
    DAUGHTER = 'DT'
    OTHER = 'OT'

    MEMBER_TYPE_CHOICES = [
        (PARENT, 'Parent'),
        (SON, 'Son'),
        (DAUGHTER, 'Daughter'),
        (OTHER, 'Other'),
    ]

    first_name = models.CharField(max_length=50, help_text="Enter your first name")
    last_name = models.CharField(max_length=50, help_text="Enter your last name")
    date_of_birth = models.DateField(help_text="Enter date of birth")
    type_of_member = models.CharField(max_length=2, choices=MEMBER_TYPE_CHOICES, default=OTHER)
    family_id = models.ForeignKey(Family, related_name='members', on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse('familymember-detail', args=[str(self.id)])

famtrack/memberapp/models.py
from django.db import models

# Create your models here.

famtrack/familyapp/forms.py
from django import forms
from .models import Family, FamilyMember

class FamilyForm(forms.ModelForm):
    class Meta:
        model = Family
        fields = ['family_name', 'address']

famtrack/familyapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Family, FamilyMember
from django.views import generic

# Create your views here.
def index(request):
    num_families = Family.objects.all().count()
    num_members = FamilyMember.objects.all().count()

    #num_parents = FamilyMember.objects.filter(type_of_member_description='Parent').count()

    context = {
        'num_families': num_families,
        'num_members': num_members,
        #'num_parents': num_parents,
    }

    #return HttpResponse("Association of Family Members")
    return render(request, 'index.html', context=context)

def about(request):
    return render(request, 'about.html')

#Generic class-based view - it queries the db to get all records for the specified models
class FamilyListView(generic.ListView):
    model = Family
    context_object_name ='family_list'
    ordering = ['id']
 
class FamilyMemberDetailView(generic.DetailView):
    model = FamilyMember

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        family_id = self.object.id
        context['familymembers'] = FamilyMember.objects.filter(family_id=family_id)
        context['family'] = Family.objects.get(id=family_id)
        return context

famtrack/memberapp/views.py
from django.shortcuts import render

# Create your views here.

famtrack/templates/about.html
{% extends "base.html" %}

{% block content %}
<h1>About Us</h1>


{% endblock %}

famtrack/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}
    <title>Membership Administration Application</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">MBA</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'family-list' %}">All Families</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contributions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Carousel -->
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'save1.jpeg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>First slide label</h5>
                    <p>Some representative placeholder content for the first slide.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'save2.jpeg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Second slide label</h5>
                    <p>Some representative placeholder content for the second slide.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'save3.jpeg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Third slide label</h5>
                    <p>Some representative placeholder content for the third slide.</p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'family-list' %}">All Families</a></li>
                    <li><a href="">Contributions</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
        </div>
    </div>
</body>

</html>

famtrack/templates/family/familymember_list.html
{% extends "base.html" %}

{% block content %}
<h1>Family Member</h1>
{% if familymember_list %}
<ul>
    {% for FamilyMember in familymember_list %}
    <li><a href="{{familymember.get_absolute_url}}">{{familymember.family_id}}</a>
        ({{familymember.first_name}}) ({{familymember.last_name}})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no families in the database.</p>
{% endif %}
{% endblock %}

famtrack/templates/familyapp/family_list.html
{% extends "base.html" %}

{% block content %}
<h1>Fahms</h1>
{% if family_list %}
<ul>
    {% for family in family_list %}
    <li><a href="{{family.get_absolute_url}}">({{family.id}}){{family.family_name}}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no families in the database.</p>
{% endif %}
{% endblock %}

famtrack/templates/familyapp/familymember_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Family: {{ familymember.family_name }}</h1>
{% for member in familymembers %}
<p><strong>First Name: </strong><a href="">{{ member.first_name }}</a></p>
<p><strong>Last Name: </strong>{{ member.last_name }}</p>
<p><strong>Date of Birth: </strong>{{ member.date_of_birth }}</p>
<p><strong>Type of Member: </strong>{{ member.get_type_of_member_display }}</p>
{% endfor %}
{% endblock %}

famtrack/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Membership Administration Application</h1>
<p>Welcome to Famtrack</p>
<h2>Family Overview</h2>
<p>This is the dashboard:</p>
<ul>
    <li><strong>Total families:</strong> {{num_families}}</li>
    <li><strong>Total members:</strong> {{num_members}}</li>
</ul>
{% endblock %}